# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' calculate partial AUC
#' @param time vector of time values
#' @param dv concentration measurements
#' @param range vector of min and max value of the partial auc range
#' @noRd
auc_partial_cpp <- function(time, dv, range) {
    .Call('_mrgmisc_auc_partial_cpp', PACKAGE = 'mrgmisc', time, dv, range)
}

#' give the min value up to that point
#' @param x A numeric vector of values
#' @details
#' useful for safety analyses where an event may be defined as a certain change
#' in a biomarker, so need to see how the current measurement compares to the minimum
#' value up to that point
#' @examples 
#'min_through(c(4, 3, 3, 2, 4, 1))
#'min_through(c(NA, 2))
#' @export
min_through <- function(x) {
    .Call('_mrgmisc_min_through', PACKAGE = 'mrgmisc', x)
}

#' give the max value up to that point
#' @param x A numeric vector of values
#' @details
#' useful for safety analyses where an event may be defined as a certain change
#' in a biomarker, so need to see how the current measurement compares to the maximum
#' value up to that point
#' @examples 
#'max_through(c(4, 3, 3, 2, 5, 1))
#'max_through(c(NA, 2, 1, 4, 2))
#' @export
max_through <- function(x) {
    .Call('_mrgmisc_max_through', PACKAGE = 'mrgmisc', x)
}

padLeft <- function(strings, numChars, paddingChar) {
    .Call('_mrgmisc_padLeft', PACKAGE = 'mrgmisc', strings, numChars, paddingChar)
}

#' given a set of bin ranges, assign each value to a bin
#' @details
#' Given a set of quantiles/bins/etc established from a separate dataset, it can 
#' be useful to assign the same bins to new or simulated data for comparisons
#' or to do additional analysis such as assign dropouts etc. This function can be
#' used to take the breakpoints to establish bins quickly and easily
#' @param x A numeric vector of values
#' @param left,right Boundary values
#' @noRd
set_bins_cpp <- function(x, left, right) {
    .Call('_mrgmisc_set_bins_cpp', PACKAGE = 'mrgmisc', x, left, right)
}

